# Generated by Django 5.2.9 on 2026-01-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominant_emotion', models.CharField(blank=True, max_length=50)),
                ('emotion_distribution', models.JSONField(default=dict, help_text='Percentage breakdown of detected emotions')),
                ('sarcasm_instances', models.PositiveIntegerField(default=0)),
                ('conflict_instances', models.PositiveIntegerField(default=0)),
                ('window_start', models.DateTimeField()),
                ('window_end', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Emotion Snapshot',
                'verbose_name_plural': 'Emotion Snapshots',
                'ordering': ['window_start'],
            },
        ),
        migrations.CreateModel(
            name='EncryptedMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_blob', models.BinaryField(help_text='AES-GCM encrypted data - server cannot decrypt')),
                ('iv', models.BinaryField(help_text='12-byte IV required for decryption')),
                ('data_type', models.CharField(default='general', help_text='Type of encrypted data for client-side routing', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Encrypted Metadata',
                'verbose_name_plural': 'Encrypted Metadata',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('title', models.CharField(blank=True, default='', help_text='Optional user-provided title for the session', max_length=255)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
