# Generated by Django 5.2.9 on 2026-01-08 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant_sessions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('duration_seconds', models.PositiveIntegerField()),
                ('dominant_emotion', models.CharField(max_length=50)),
                ('dominant_emotion_percentage', models.FloatField(help_text='Percentage of time this emotion was dominant')),
                ('emotion_breakdown', models.JSONField(default=dict, help_text='{"happiness": 35.5, "neutral": 40.2, ...}')),
                ('total_readings', models.PositiveIntegerField(default=0, help_text='Number of emotion readings captured')),
                ('average_confidence', models.FloatField(default=0.0, help_text='Average confidence across all readings')),
                ('title', models.CharField(blank=True, default='', help_text='Optional user-provided session title', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emotion_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotion Session',
                'verbose_name_plural': 'Emotion Sessions',
                'ordering': ['-ended_at'],
            },
        ),
    ]
