# Generated by Django 5.2.9 on 2026-01-06 17:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('preferred_hud_intensity', models.CharField(choices=[('subtle', 'Subtle - Minimal visual indicators'), ('moderate', 'Moderate - Balanced feedback'), ('prominent', 'Prominent - Clear, visible indicators')], default='moderate', help_text='Controls the visibility of emotion indicators', max_length=20)),
                ('enable_topic_anchoring', models.BooleanField(default=True, help_text='Show topic anchors to help re-engage in conversation (ADHD)')),
                ('enable_sarcasm_detection', models.BooleanField(default=True, help_text='Highlight potential sarcasm/irony (ASD)')),
                ('enable_audio_analysis', models.BooleanField(default=True, help_text='Analyze vocal prosody for emotion detection')),
                ('enable_facial_analysis', models.BooleanField(default=True, help_text='Analyze facial expressions for emotion detection')),
                ('emotion_baseline', models.JSONField(blank=True, default=dict, help_text='Encrypted personal baseline for emotion calibration')),
                ('sensory_preferences', models.JSONField(blank=True, default=dict, help_text='Color schemes, animation preferences, etc.')),
                ('auto_delete_sessions', models.BooleanField(default=False, help_text='Automatically delete session data after 24 hours')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
